### ISSUE TITLE
How to track channel labels and locations?

### ISSUE THREAD

**Issue by cboulay** [iscoe/ezmsg#43]
If I have a source Unit that has information about channel labels and locations, what is the recommended way to relay that to downstream Units? It's too much information to put into a e.g. `SpaceAxis` and transmit with every message.

So do I add a META_OUTPUT port to my Unit and transmit it once when I get that information and again whenever it changes? Is there any way to guarantee that this port is transmitted first so that downstream Units will receive the updated metadata before receiving streaming data with the new format?

**Comment by griffinmilsap** [comment]
In practice, I subclass AxisArray and add custom fields to it that track the extra information.  I tend to take it on the nose serializing that info with every message with the understanding that ezmsg is ... _very_ .. fast.  Seems inefficient, but it is the vastly simpler solution.  Given ezmsg's message cacheing under the hood, the impact is actually quite minimal.

If you really want to do this with a meta_output stream, I recommend setting up receivers for your meta_output that wait until that metadata is received before processing any EEG messages.  I can post an example impl if you're interested

**Comment by griffinmilsap** [comment]
As a matter of fact, if you do it like this:
``` python
@dataclass
class EEGMessage(AxisArray):
    ch_names: typing.List[str]
    ch_locs: npt.ndarray
```

Under the hood, message passing is implemented with only one copy (with zero-copy reads) for any data type that uses the array API.  It might just be faster than you think ;)

**Comment by griffinmilsap** [comment]
closing for now, but this issue should probably be referenced in a future "Patterns" or FAQ page (#54)
