### ISSUE TITLE
Request: sigproc Spectrogram Collection

### ISSUE THREAD

**Issue by cboulay** [iscoe/ezmsg#44]
I think it's a pretty common use-case to put a Window in front of Spectrum. This should probably be in a pre-made collection with easy-access settings.

(1-of-several requests to get at SpectralBandpower)

**Comment by griffinmilsap** [comment]
@cboulay Sorry for the delay in response on these diligent issue reports, I was taking a short break.  Agreed that we should have a dedicated collection; unclear to me what good default names are for these axes.  As you noted, my ezmsg-panel implementation uses a "win" dimension, and the default names need to be changed from there on forward.

I think it might be a bit surprising for the spectrum unit to rename the requested axis to a time axis without being explicitly told to do so; I actually think the core issue is with having a default axis in the existing sigproc units; which was only done for backward compatibility.  Perhaps we just deprecate the default axis names and move on?
