### ISSUE TITLE
bugfix: Spectrum should pop transformed axis out of out_msg.axes

### ISSUE THREAD

**Issue by cboulay** [iscoe/ezmsg#48]
The outgoing message has `axes` field that includes the old axis (e.g. "time") even if it is no longer present because it was overwritten by "freq".

Editing [this code](https://github.com/iscoe/ezmsg/blob/dev/extensions/ezmsg-sigproc/ezmsg/sigproc/spectral.py#L126-L128) should work:

```python
        new_dims = [d for d in message.dims]
        if self.SETTINGS.out_axis is not None:
            new_dims[axis_idx] = self.SETTINGS.out_axis
            if self.SETTINGS.out_axis != axis_name:
                _ = new_axes.pop(axis_name)
```

**Comment by griffinmilsap** [comment]
Merged into dev; thanks!
