### ISSUE TITLE
gen_to_unit: settings should use `signature` instead of `getfullargspec`

### ISSUE THREAD

**Issue by cboulay** [iscoe/ezmsg#91]
I think it's the same issue as here: https://github.com/joblib/joblib/issues/1164

I'm guessing that the settings-reading code in gen_to_unit was written before the `@consumer` wrapper was written.

If you dive into `getfullargspec`, the first thing it does is call `_signature_from_callable(func, follow_wrapper_chains=False, ...)`.
If we could set that to `follow_wrapper_chains=True` then it would properly inspect the wrapped-function's arguments. But that is hard-coded.

In our case, this hasn't been too detrimental so far because we are still able to get the settings annotations using `get_type_hints(func)` but this doesn't know anything about default values.

**Comment by griffinmilsap** [comment]
Hmm.  gen_to_unit is a bit of a beast -- @pperanich when you find time could you weigh in?

**Comment by cboulay** [comment]
I've already made some good progress and added some unit tests. I'll make a PR soon.
